### ISSUE TITLE
Cách sử dụng model sau khi train

### ISSUE THREAD

**Issue by TuHuynh296** [vudaoanhtuan/vietnamese-tone-prediction#1]
Model được lưu dưới dạng file dict chứa 2 keys model và optimize, làm sao để mình có thể predict được một câu không có dấu khác ở ngoài? Phải tiền xử lý nó trước và đưa về vector như thế nào vậy bạn ?

**Comment by vudaoanhtuan** [comment]
bạn chạy file translate.py với các tham số phù hợp hoặc bạn có thể đọc code trong file đó và làm tương tự để predict
